apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-pull-sa
  namespace: three-tier
  annotations:
    # Replace with the actual ARN of your AWS IAM Role that has ECR read permissions
    eks.amazonaws.com/role-arn: arn:aws:iam::252610334383:role/iam-role-ec2